name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Navigate to subdirectory
      run: cd app
    - name: List files
      run: ls -R

    - name: Install dependencies
      run: npm install 
    - name: Build file
      run: npm run build
    - name: Run tests
      run: npm test
